# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,museomics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Maniola jurtina
# Path to reference genome file in FASTA format
reference_genome_path: 
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: 
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    time_period: 2022
    data_type: contemporary, paired-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_01_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_02_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_03_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_04_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_05_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_06_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_07_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_08_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_09_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_10_J_2022
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_11_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_12_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_13_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_14_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_15_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_16_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_17_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_18_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_19_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_20_S_2022
  -
    time_period: 1985
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_21_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_22_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_23_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_24_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_25_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_26_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_27_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_28_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_29_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_30_J_1985
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_31_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_32_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_33_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_34_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_35_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_36_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_37_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_38_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_39_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_40_S_1985
  -
    time_period: 1950
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_41_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_42_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_43_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_44_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_45_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_46_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_47_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_48_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_49_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_50_J_1950
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_51_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_52_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_53_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_54_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_55_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_56_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_57_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_58_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_59_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_60_S_1950
  -
    time_period: 1915
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_61_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_62_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_63_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_64_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_65_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_66_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_67_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_68_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_69_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_70_J_1915
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_71_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_72_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_73_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_74_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_75_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_76_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_77_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_78_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_79_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Maniola_jurtina/MaJu_80_S_1915