# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,museomics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Coenonympha tullia
# Path to reference genome file in FASTA format
reference_genome_path: 
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: 
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    time_period: 2022
    data_type: contemporary, paired-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_01_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_02_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_03_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_04_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_05_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_06_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_07_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_08_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_09_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_10_J_2022
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_11_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_12_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_13_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_14_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_15_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_16_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_17_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_18_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_19_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_20_S_2022
  -
    time_period: 1985
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_21_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_22_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_23_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_24_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_25_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_26_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_27_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_28_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_29_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_30_J_1985
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_31_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_32_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_33_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_34_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_35_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_36_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_37_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_38_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_39_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_40_S_1985
  -
    time_period: 1950
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_41_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_42_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_43_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_44_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_45_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_46_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_47_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_48_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_49_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_50_J_1950
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_51_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_52_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_53_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_54_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_55_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_56_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_57_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_58_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_59_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_60_S_1950
  -
    time_period: 1915
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_61_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_62_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_63_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_64_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_65_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_66_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_67_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_68_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_69_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_70_J_1915
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_71_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_72_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_73_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_74_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_75_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_76_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_77_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_78_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_79_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Coenonympha_tullia/CoTu_80_S_1915