# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,museomics,freebayes:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed.
species_name: Gonepteryx rhamni
# Path to reference genome.
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Gonepteryx_rhamni/EG_GonRha_22032024_genomic.fna
# Partition size of genome in base pairs
partition_size: 100000
# Sample setup. List of dictionaries listing the configuration for each sample.
sample_list:
  -
    # Name of sample.
    sample_name: GoRh_ind50
    # Name of sample group.
    sample_group: individual_extraction
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps/Gonepteryx_rhamni/mapping/poolseq/individual_extraction/filtered_alignment/GoRh_ind50/GoRh_ind50.filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:    
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2
  -
    # Name of sample.
    sample_name: GoRh_pool50
    # Name of sample group.
    sample_group: pooled_extraction
    # Path to BAM file.
    bam_file: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps/Gonepteryx_rhamni/mapping/poolseq/pooled_extraction/filtered_alignment/GoRh_pool50/GoRh_pool50.filtered.bam
    # Directory for intermediary files.
    working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
    # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
    output_directory_path:
    # Freebayes settings
    freebayes_settings:
      sample_ploidy: 100
      best_n_alleles: 3
      min_alternate_fraction: 0
      min_alternate_count: 2