# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,museomics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Gonepteryx rhamni
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/reference_genomes/Gonepteryx_rhamni/EG_GonRha_22032024_genomic.fna
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path:
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    time_period: 2022
    data_type: contemporary, paired-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_01_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_02_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_03_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_04_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_05_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_06_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_07_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_08_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_09_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_10_J_2022
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_11_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_12_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_13_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_14_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_15_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_16_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_17_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_18_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_19_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_20_S_2022
  -
    time_period: 1985
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_21_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_22_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_23_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_24_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_25_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_26_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_27_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_28_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_29_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_30_J_1985
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_31_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_32_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_33_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_34_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_35_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_36_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_37_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_38_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_39_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_40_S_1985
  -
    time_period: 1950
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_41_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_42_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_43_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_44_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_45_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_46_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_47_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_48_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_49_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_50_J_1950
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_51_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_52_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_53_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_54_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_55_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_56_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_57_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_58_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_59_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_60_S_1950
  -
    time_period: 1915
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_61_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_62_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_63_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_64_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_65_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_66_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_67_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_68_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_69_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_70_J_1915
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_71_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_72_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_73_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_74_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_75_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_76_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_77_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_78_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_79_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Gonepteryx_rhamni/GoRh_80_S_1915