# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,museomics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Name of species being analyzed
species_name: Thymelicus lineola
# Path to reference genome file in FASTA format
reference_genome_path: 
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/museomics/steps
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: 
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    time_period: 2022
    data_type: contemporary, paired-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_01_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_02_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_03_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_04_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_05_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_06_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_07_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_08_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_09_J_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_10_J_2022
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_11_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_12_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_13_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_14_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_15_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_16_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_17_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_18_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_19_S_2022
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_20_S_2022
  -
    time_period: 1985
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_21_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_22_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_23_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_24_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_25_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_26_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_27_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_28_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_29_J_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_30_J_1985
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_31_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_32_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_33_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_34_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_35_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_36_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_37_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_38_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_39_S_1985
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_40_S_1985
  -
    time_period: 1950
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_41_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_42_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_43_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_44_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_45_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_46_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_47_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_48_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_49_J_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_50_J_1950
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_51_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_52_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_53_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_54_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_55_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_56_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_57_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_58_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_59_S_1950
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_60_S_1950
  -
    time_period: 1915
    data_type: historic, single-end
    populations:
      -
        population_name: Jutland
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_61_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_62_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_63_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_64_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_65_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_66_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_67_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_68_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_69_J_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_70_J_1915
      -
        population_name: Zealand
        sample_folder_list:
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_71_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_72_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_73_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_74_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_75_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_76_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_77_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_78_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_79_S_1915
          - /faststorage/project/EcoGenetics/BACKUP/museomics/Thymelicus_lineola/ThLi_80_S_1915